server:
  port: 8880

test:
  hello: hello-world

# 增加数据库连接
spring:
  datasource:
    username: wiki
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wiki?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimeZone=Asia/Shanghai

# 配置mybatis所有的mapper.xml所在的路径
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml